"use client";

export default function Footer() {
  return (
    <footer style={{
      borderTop: "1px solid var(--bg-border)",
      marginTop: 32,
      padding: "36px 24px 24px",
    }}>
      <div style={{
        maxWidth: 1200, margin: "0 auto",
        display: "flex", flexWrap: "wrap",
        justifyContent: "space-between", gap: 28,
      }}>
        {/* Left — Brand */}
        <div style={{ maxWidth: 320 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
            <div style={{
              width: 26, height: 26, borderRadius: 8,
              background: "linear-gradient(135deg, #2563eb, #06b6d4)",
              display: "flex", alignItems: "center", justifyContent: "center",
              fontSize: 12, fontWeight: 700, color: "white",
            }}>BI</div>
            <span style={{ fontWeight: 700, fontSize: "0.875rem" }}>bi-platform</span>
          </div>
          <p style={{ fontSize: "0.78rem", color: "var(--text-muted)", lineHeight: 1.55 }}>
            Multi-agent AI analytics platform. Upload your data and get
            an executive report in under 30 seconds — powered by LangGraph,
            Groq, and a 4-model forecasting ensemble.
          </p>
        </div>

        {/* Middle — Project Links */}
        <div>
          <p className="mono" style={{ marginBottom: 10, color: "var(--text-secondary)" }}>
            Project
          </p>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <a href="https://github.com/dheeraj116232/multi-agent-bi-platform"
               target="_blank" rel="noopener noreferrer"
               style={{ fontSize: "0.78rem", color: "var(--text-muted)", textDecoration: "none" }}>
              ⭐ GitHub Repository
            </a>
            <a href="https://multi-agent-bi-platform.onrender.com/docs"
               target="_blank" rel="noopener noreferrer"
               style={{ fontSize: "0.78rem", color: "var(--text-muted)", textDecoration: "none" }}>
              📘 API Documentation
            </a>
            <a href="https://github.com/dheeraj116232/multi-agent-bi-platform#readme"
               target="_blank" rel="noopener noreferrer"
               style={{ fontSize: "0.78rem", color: "var(--text-muted)", textDecoration: "none" }}>
              📄 Architecture & Docs
            </a>
          </div>
        </div>

        {/* Right — Connect */}
        <div>
          <p className="mono" style={{ marginBottom: 10, color: "var(--text-secondary)" }}>
            Connect
          </p>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <a href="https://github.com/dheeraj116232"
               target="_blank" rel="noopener noreferrer"
               style={{ fontSize: "0.78rem", color: "var(--text-muted)", textDecoration: "none" }}>
              💻 GitHub Profile
            </a>
            <a href="https://www.linkedin.com/in/dheerajkumar116232/"
               target="_blank" rel="noopener noreferrer"
               style={{ fontSize: "0.78rem", color: "var(--text-muted)", textDecoration: "none" }}>
              💼 LinkedIn
            </a>
            <a href="mailto:your.dheerajl116232@gmail.com"
               style={{ fontSize: "0.78rem", color: "var(--text-muted)", textDecoration: "none" }}>
              ✉️ Email Me
            </a>
          </div>
        </div>
      </div>

      {/* Tech stack badges */}
      <div style={{
        maxWidth: 1200, margin: "20px auto 0",
        display: "flex", flexWrap: "wrap", gap: 6,
      }}>
        {["LangGraph","FastAPI","Next.js","Groq","XGBoost","Prophet","PostgreSQL","Matplotlib"].map(t => (
          <span key={t} style={{
            fontSize: "0.68rem", padding: "3px 10px", borderRadius: 999,
            background: "rgba(255,255,255,0.04)",
            border: "1px solid var(--bg-border)",
            color: "var(--text-muted)",
          }}>{t}</span>
        ))}
      </div>

      {/* Bottom bar */}
      <div style={{
        maxWidth: 1200, margin: "18px auto 0",
        paddingTop: 16, borderTop: "1px solid rgba(255,255,255,0.04)",
        display: "flex", flexWrap: "wrap", justifyContent: "space-between",
        alignItems: "center", gap: 10,
      }}>
        <p className="mono" style={{ color: "var(--text-muted)" }}>
          © 2026 Dheeraj Kumar · MIT License
        </p>
        <p className="mono" style={{ color: "var(--text-muted)" }}>
          GENERATED BY 5 AI AGENTS · LANGRAPH + GROQ + XGBOOST
        </p>
      </div>
    </footer>
  );
}